// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-LH42ncOhVL9p54dttxxEyZFqeXgICM',
    appId: '1:22727084704:web:46d0d3f83a8d8a601817c5',
    messagingSenderId: '22727084704',
    projectId: 'plant-monitoring-cf196',
    authDomain: 'plant-monitoring-cf196.firebaseapp.com',
    databaseURL:
        'https://plant-monitoring-cf196-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'plant-monitoring-cf196.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLltrtiY4f1tN-iLhxy4XAjGn_3HvAxE',
    appId: '1:22727084704:android:ab375022cfaf43891817c5',
    messagingSenderId: '22727084704',
    projectId: 'plant-monitoring-cf196',
    databaseURL:
        'https://plant-monitoring-cf196-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'plant-monitoring-cf196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArkpaY3bU4Y3FEnH4u1RcOy9bqGJLnJRw',
    appId: '1:22727084704:ios:ed67825c3c5742811817c5',
    messagingSenderId: '22727084704',
    projectId: 'plant-monitoring-cf196',
    databaseURL:
        'https://plant-monitoring-cf196-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'plant-monitoring-cf196.appspot.com',
    androidClientId:
        '22727084704-obcb7mj2rql6t1gsf103cqs8hki9g6ba.apps.googleusercontent.com',
    iosClientId:
        '22727084704-au2ikrcplthms93dbepf26b8bqdnb0aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArkpaY3bU4Y3FEnH4u1RcOy9bqGJLnJRw',
    appId: '1:22727084704:ios:ed67825c3c5742811817c5',
    messagingSenderId: '22727084704',
    projectId: 'plant-monitoring-cf196',
    databaseURL:
        'https://plant-monitoring-cf196-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'plant-monitoring-cf196.appspot.com',
    androidClientId:
        '22727084704-obcb7mj2rql6t1gsf103cqs8hki9g6ba.apps.googleusercontent.com',
    iosClientId:
        '22727084704-au2ikrcplthms93dbepf26b8bqdnb0aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantMonitoringApp',
  );
}
